name: "Github Pages 🚢"
on:
  push:
    branches: [ "actions" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: "Build Artifacts 🏗️"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    name: "Deploy Pages 📃"
    needs: build
    
    environment:
      name: github-pages
      url: https://jeffmur.dev

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
